name: Deploy to GCP Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: ${{ fromJson(secrets.GCP_CONFIG).WIF_PROVIDER }}
          service_account: ${{ fromJson(secrets.GCP_CONFIG).WIF_SERVICE_ACCOUNT }}

      - name: 'Deploy to Cloud Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v4'
        with:
          name: ${{ fromJson(secrets.GCP_CONFIG).FUNCTION_NAME }}
          runtime: 'python311'
          region: ${{ fromJson(secrets.GCP_CONFIG).REGION }}
          entry_point: 'main'
          env_vars: |-
            PROJECT_ID=${{ fromJson(secrets.GCP_CONFIG).PROJECT_ID }}
            DATASET_ID=${{ fromJson(secrets.GCP_CONFIG).DATASET_ID }}
            SECRET_ID=BING_API_KEY
            SITE_URL=${{ fromJson(secrets.GCP_CONFIG).SITE_URL }}
