name: Deploy to GCP Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/454656526702/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@web-alexisgomel.iam.gserviceaccount.com'

      - name: 'Deploy to Cloud Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          name: 'bing-webmaster-updater'
          runtime: 'python311'
          region: 'europe-west1' # Moved to EU to match Search Console data
          entry_point: 'main'
          trigger_http: true
          allow_unauthenticated: false
